name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (free/open-source)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip libffi-dev libssl-dev libsndfile1 curl openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/.android/sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=${{ github.workspace }}/.android/sdk" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:${{ github.workspace }}/.android/sdk/cmdline-tools/latest/bin:${{ github.workspace }}/.android/sdk/platform-tools:${PATH}" >> $GITHUB_ENV
          python -m pip install --upgrade pip
          python -m pip install buildozer cython==0.29.36 virtualenv

      - name: Verify Java 17
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          which java || true
          java -version

      - name: Install Android cmdline-tools + SDK/NDK (official free)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p cmdline-tools
          unzip -q -o cmdtools.zip -d cmdline-tools
          [ -d cmdline-tools/cmdline-tools ] && mv -f cmdline-tools/cmdline-tools cmdline-tools/latest || true
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$JAVA_HOME/bin:$PATH"

          # accept licenses twice
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          yes | sdkmanager --licenses || true

          # install stable components with AIDL
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;33.0.2" \
            "build-tools;34.0.0" \
            "ndk;25.1.8937393" \
            "cmake;3.22.1"

          echo "== build-tools installed =="
          ls -al "$ANDROID_SDK_ROOT/build-tools" || true
          echo "== AIDL search =="
          find "$ANDROID_SDK_ROOT/build-tools" -maxdepth 2 -name aidl -print || true

          # Map SDK to buildozer's expected legacy layout
          LEGACY="$HOME/.buildozer/android/platform/android-sdk"
          mkdir -p "$LEGACY"
          # link whole SDK root
          if [ ! -e "$LEGACY" ]; then
            mkdir -p "$(dirname "$LEGACY")"
            ln -s "$ANDROID_SDK_ROOT" "$LEGACY"
          fi
          # ensure legacy tools/bin exists and link sdkmanager there
          mkdir -p "$LEGACY/tools/bin"
          if [ ! -e "$LEGACY/tools/bin/sdkmanager" ]; then
            ln -s "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "$LEGACY/tools/bin/sdkmanager"
          fi
          # ensure build-tools directory exists (it should via root link, but double-ensure)
          [ -d "$LEGACY/build-tools" ] || ln -s "$ANDROID_SDK_ROOT/build-tools" "$LEGACY/build-tools"

      - name: Cache .buildozer (free)
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer (ensure aidl/sdkmanager)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
          PATH: ${{ env.ANDROID_SDK_ROOT }}/build-tools/34.0.0:${{ env.ANDROID_SDK_ROOT }}/build-tools/33.0.2:${{ env.ANDROID_SDK_ROOT }}/platform-tools:${{ env.ANDROID_SDK_ROOT }}/cmdline-tools/latest/bin:${{ env.JAVA_HOME }}/bin:${{ env.PATH }}
        run: |
          set -e
          python -V
          echo "# which aidl"
          which aidl || (echo "aidl not in PATH"; exit 1)
          echo "# which sdkmanager"
          which sdkmanager || (echo "sdkmanager not in PATH"; exit 1)
          echo "# legacy sdkmanager exists?"
          test -x "$HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager" || (echo "legacy sdkmanager link missing"; ls -al "$HOME/.buildozer/android/platform/android-sdk/tools/bin" || true; exit 1)
          echo "# legacy build-tools exists?"
          test -d "$HOME/.buildozer/android/platform/android-sdk/build-tools" || (echo "legacy build-tools link missing"; exit 1)

          export ANDROIDSDK="$ANDROID_SDK_ROOT"
          export ANDROIDNDK="$ANDROID_SDK_ROOT/ndk/25.1.8937393"
          export ANDROIDAPI=34
          export NDKAPI=23

          buildozer android debug

      - name: Upload APK (free artifact)
        uses: actions/upload-artifact@v4
        with:
          name: toopen4-apk
          path: bin/*.apk
