name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip libffi-dev libssl-dev libsndfile1 openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython==0.29.36 virtualenv
      - name: Accept Android licenses and build
        run: |
          yes | sdkmanager --licenses || true
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: toopen4-apk
          path: bin/*.apk
