name: Android APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (free)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip libffi-dev libssl-dev libsndfile1 curl rsync ca-certificates openjdk-17-jdk
          python -m pip install --upgrade pip
          python -m pip install buildozer cython==0.29.36 virtualenv
          git --version

      - name: Single SDK env (avoid conflicts)
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${{ github.workspace }}/.android/sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=" >> $GITHUB_ENV
          echo "PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:${{ github.workspace }}/.android/sdk/cmdline-tools/latest/bin:${{ github.workspace }}/.android/sdk/platform-tools:${{ github.workspace }}/.android/sdk/build-tools/34.0.0:${{ github.workspace }}/.android/sdk/build-tools/33.0.2:${PATH}" >> $GITHUB_ENV
          echo "GIT_TERMINAL_PROMPT=0" >> $GITHUB_ENV
          echo "GIT_ASKPASS=true" >> $GITHUB_ENV

      - name: Install Android SDK/NDK (cmdline-tools)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: |
          set -e
          mkdir -p "$ANDROID_SDK_ROOT"
          cd "$ANDROID_SDK_ROOT"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          mkdir -p cmdline-tools
          unzip -q -o cmdtools.zip -d cmdline-tools
          if [ -d cmdline-tools/cmdline-tools ]; then mv -f cmdline-tools/cmdline-tools cmdline-tools/latest; fi
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$JAVA_HOME/bin:$PATH"
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          yes | sdkmanager --licenses || true
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;33.0.2" \
            "build-tools;34.0.0" \
            "ndk;25.1.8937393" \
            "cmake;3.22.1"

      - name: Prepare buildozer internal SDK (copy + wrapper)
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          set -e
          INTERNAL="$HOME/.buildozer/android/platform/android-sdk"
          rm -rf "$HOME/.buildozer/android/platform" || true
          mkdir -p "$INTERNAL/cmdline-tools/latest/bin" "$INTERNAL/tools/bin" "$INTERNAL/platform-tools" "$INTERNAL/build-tools"
          rsync -a "$ANDROID_SDK_ROOT/platform-tools/" "$INTERNAL/platform-tools/"
          rsync -a "$ANDROID_SDK_ROOT/build-tools/" "$INTERNAL/build-tools/"
          rsync -a "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/" "$INTERNAL/cmdline-tools/latest/bin/"

          # legacy tools/bin/sdkmanager → 항상 cmdline-tools를 호출하는 래퍼
          cat > "$INTERNAL/tools/bin/sdkmanager" <<'SH'
#!/usr/bin/env bash
SDK_ROOT="${ANDROID_SDK_ROOT:-$HOME/.buildozer/android/platform/android-sdk}"
REAL="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
exec "$REAL" "$@"
SH
          chmod +x "$INTERNAL/tools/bin/sdkmanager"

          # android 존재 체크 우회 스텁
          printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$INTERNAL/tools/bin/android"
          chmod +x "$INTERNAL/tools/bin/android"

      - name: Preflight checks
        run: |
          set -e
          echo ">>> java"; which java; java -version || true
          echo ">>> PATH sdkmanager"; which sdkmanager || true
          echo ">>> INTERNAL wrapper"; ls -al "$HOME/.buildozer/android/platform/android-sdk/tools/bin" || true
          echo ">>> aidl"; which aidl || true
          echo ">>> ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"

      - name: Cache .buildozer (free)
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer (full log)
        env:
          ANDROIDSDK: $HOME/.buildozer/android/platform/android-sdk
          ANDROIDNDK: ${{ env.ANDROID_SDK_ROOT }}/ndk/25.1.8937393
          ANDROIDAPI: '34'
          NDKAPI: '23'
        run: |
          set -e
          mkdir -p .buildozer
          buildozer --log-level=2 android debug 2>&1 | tee .buildozer/.full_build_output
          cp .buildozer/.full_build_output .buildozer/.full_build_output.copy || true
          test -f bin/*.apk || exit 1

      - name: Upload APK (free artifact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: toopen4-apk
          path: bin/*.apk

      - name: Extract 15-line error snippet (robust)
        if: failure()
        run: |
          mkdir -p error_snippet
          tail -n 15 .buildozer/android/platform/build-*/build/bootstraps/*/build.log > error_snippet/error_snippet_15.txt 2>/dev/null || \
          tail -n 15 .buildozer/android/platform/build-*/build/*.log > error_snippet/error_snippet_15.txt 2>/dev/null || \
          tail -n 15 .buildozer/.full_build_output.copy > error_snippet/error_snippet_15.txt 2>/dev/null || \
          echo "[no logs] build stopped before logs were created" > error_snippet/error_snippet_15.txt
          zip -j error_snippet/WordMaster_error_snippet.zip error_snippet/error_snippet_15.txt

      - name: Upload error snippet + full log (artifact)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-snippet-15
          path: |
            error_snippet/error_snippet_15.txt
            error_snippet/WordMaster_error_snippet.zip
            .buildozer/.full_build_output.copy
